EscortWithSuitcaseActionWalk._walk_anim_velocities.stand.ntl = EscortWithSuitcaseActionWalk._walk_anim_velocities.stand.hos
EscortWithSuitcaseActionWalk._walk_anim_velocities.stand.hos.run = EscortWithSuitcaseActionWalk._walk_anim_velocities.stand.hos.walk
EscortWithSuitcaseActionWalk._walk_anim_velocities.stand.cbt = EscortWithSuitcaseActionWalk._walk_anim_velocities.stand.hos
EscortWithSuitcaseActionWalk._walk_anim_velocities.crouch = EscortWithSuitcaseActionWalk._walk_anim_velocities.stand
EscortWithSuitcaseActionWalk._walk_anim_velocities.wounded = EscortWithSuitcaseActionWalk._walk_anim_velocities.stand

EscortWithSuitcaseActionWalk._walk_anim_lengths.stand.ntl = EscortWithSuitcaseActionWalk._walk_anim_lengths.stand.hos
EscortWithSuitcaseActionWalk._walk_anim_lengths.stand.hos.run = EscortWithSuitcaseActionWalk._walk_anim_lengths.stand.hos.walk
EscortWithSuitcaseActionWalk._walk_anim_lengths.stand.cbt = EscortWithSuitcaseActionWalk._walk_anim_lengths.stand.hos
EscortWithSuitcaseActionWalk._walk_anim_lengths.crouch = EscortWithSuitcaseActionWalk._walk_anim_lengths.stand
EscortWithSuitcaseActionWalk._walk_anim_lengths.wounded = EscortWithSuitcaseActionWalk._walk_anim_lengths.stand